apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtool-task-spawner
spec:
  template:
    spec:
      containers:
        - name: virtool
          command: ["virtool", "tasks", "spawner"]
          resources:
            limits:
              cpu: 400m
              memory: 600M
            requests:
              cpu: 200m
              memory: 300M
