apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: virtool-job-build-index
spec:
  jobTargetRef:
    backoffLimit: 1
    completions: 1
    parallelism: 1
    ttlSecondsAfterFinished: 300
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        labels:
          app: job-build-index
      spec:
        containers:
          - name: job-build-index
            image: ghcr.io/virtool/build-index:5.4.1
            imagePullPolicy: Always
            command: [run-workflow]
            envFrom:
              - configMapRef:
                  name: virtool-jobs-config
            env:
              - name: VT_PROC
                value: "2"
              - name: VT_MEM
                value: "2"
              - name: VT_REDIS_LIST_NAME
                value: "jobs_build_index"
            resources:
              limits:
                cpu: 3
                memory: 5Gi
              requests:
                cpu: 3
                memory: 5Gi
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 1
  triggers:
    - type: redis
      metadata:
        addressFromEnv: VT_REDIS_HOST
        passwordFromEnv: VT_REDIS_PASSWORD
        listName: jobs_build_index
        listLength: "1"
