apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: virtool-job-nuvs
spec:
  jobTargetRef:
    backoffLimit: 1
    completions: 1
    parallelism: 1
    ttlSecondsAfterFinished: 300
    template:
      metadata:
        annotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
        labels:
          app: job-nuvs
      spec:
        containers:
          - name: job-nuvs
            image: virtool/nuvs:5.1.0
            imagePullPolicy: Always
            command: [run-workflow]
            envFrom:
              - configMapRef:
                  name: virtool-jobs-config
            env:
              - name: VT_PROC
                value: "4"
              - name: VT_MEM
                value: "10"
              - name: VT_REDIS_LIST_NAME
                value: "jobs_nuvs"
            resources:
              limits:
                cpu: "10"
                memory: 14Gi
              requests:
                cpu: "10"
                memory: 14Gi
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 1
  triggers:
    - type: redis
      metadata:
        addressFromEnv: VT_REDIS_HOST
        passwordFromEnv: VT_REDIS_PASSWORD
        listName: jobs_nuvs
        listLength: "1"
