architecture: replicaset
replicaCount: 1
auth:
  replicaSetKey: virtool
  rootPassword: virtool
  passwords:
    - virtool
  usernames:
    - virtool
  databases:
    - virtool
arbiter:
  enabled: false



