apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtool-task-runner
  labels:
    app: VirtoolTaskRunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VirtoolTaskRunner
  template:
    metadata:
      labels:
        app: VirtoolTaskRunner
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/virtool/virtool:28.0.1
          imagePullPolicy: Always
          name: virtool-task-runner
          command: ["virtool", "tasks", "runner"]
          env:
            - name: VT_DATA_PATH
              value: "/data"
            - name: VT_HOST
              value: "0.0.0.0"
            - name: VT_MONGODB_CONNECTION_STRING
              value: "mongodb://virtool:virtool@mongo-mongodb-0.mongo-mongodb-headless.default.svc.cluster.local/virtool"
            - name: VT_OPENFGA_HOST
              value: "openfga.default.svc.cluster.local"
            - name: VT_OPENFGA_SCHEME
              value: "http"
            - name: VT_POSTGRES_CONNECTION_STRING
              value: "postgresql+asyncpg://virtool@postgresql.default.svc.cluster.local?password=virtool"
            - name: VT_REDIS_CONNECTION_STRING
              value: "redis://:virtool@redis-master.default.svc.cluster.local"
          ports:
            - containerPort: 9950
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
              ephemeral-storage: 1Gi
            requests:
              cpu: 600m
              memory: 1Gi
              ephemeral-storage: 1Gi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          nfs:
            server: 10.109.28.120
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-runner
spec:
  type: ClusterIP
  selector:
    app: VirtoolTaskRunner
  ports:
    - name: http
      port: 80
      targetPort: 9950
