apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtool-task-spawner
  labels:
    app: VirtoolTaskSpawner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VirtoolTaskSpawner
  template:
    metadata:
      labels:
        app: VirtoolTaskSpawner
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/virtool/virtool:28.0.1
          imagePullPolicy: Always
          name: virtool-task-spawner
          command: ["virtool", "tasks", "spawner"]
          env:
            - name: VT_HOST
              value: "0.0.0.0"
            - name: VT_MONGODB_CONNECTION_STRING
              value: "mongodb://virtool:virtool@mongo-mongodb-0.mongo-mongodb-headless.default.svc.cluster.local/virtool"
            - name: VT_POSTGRES_CONNECTION_STRING
              value: "postgresql+asyncpg://virtool@postgresql.default.svc.cluster.local?password=virtool"
            - name: VT_REDIS_CONNECTION_STRING
              value: "redis://:virtool@redis-master.default.svc.cluster.local"
          ports:
            - containerPort: 9950
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 600M
            requests:
              cpu: 200m
              memory: 300M
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-spawner
spec:
  type: ClusterIP
  selector:
    app: VirtoolTaskSpawner
  ports:
    - name: http
      port: 80
      targetPort: 9950
