apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtool-tasks-runner
  labels:
    app: VirtoolTasksRunner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: VirtoolTasksRunner
  template:
    metadata:
      labels:
        app: VirtoolTasksRunner
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/virtool/virtool:15.1.1
          imagePullPolicy: Always
          name: virtool-tasks-runner
          command: ["python", "run.py", "tasks"]
          env:
            - name: VT_DATA_PATH
              value: "/data"
            - name: VT_DB_CONNECTION_STRING
              value: "mongodb://virtool:virtool@mongo-mongodb-0.mongo-mongodb-headless.default.svc.cluster.local/virtool"
            - name: VT_DB_NAME
              value: "virtool"
            - name: VT_OPENFGA_SCHEME
              value: "http"
            - name: VT_OPENFGA_HOST
              value: "openfga.default.svc.cluster.local"
            - name: VT_SERVER_HOST
              value: "0.0.0.0"
            - name: VT_REDIS_CONNECTION_STRING
              value: "redis://:virtool@redis-master.default.svc.cluster.local"
            - name: VT_POSTGRES_CONNECTION_STRING
              value: "postgresql+asyncpg://virtool@postgresql.default.svc.cluster.local?password=virtool"
            - name: VT_DEV
              value: "true"
          ports:
          - containerPort: 9950
            protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 600m
              memory: 1Gi
          volumeMounts:
          - name: data
            mountPath: /data
      volumes:
      - name: data
        nfs:
            server: 10.109.28.120
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-runner
spec:
  type: ClusterIP
  selector:
    app: VirtoolTasksRunner
  ports:
    - name: http
      port: 80
      targetPort: 9950