apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtool-api-web
spec:
  template:
    spec:
      containers:
        - name: virtool
          command: ["virtool", "server", "api"]
          resources:
            limits:
              cpu: 600m
              memory: 800M
            requests:
              cpu: 400m
              memory: 400M