apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app.virtool.ca/workflow-name: create-sample
    app.virtool.ca/workflow-size: small
  name: create-sample
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: workflow-create-sample
      spec:
        containers:
          - name: workflow-create-sample
            image: ghcr.io/virtool/create-sample:4.3.4
            env:
              - name: VT_PROC
                value: "2"
              - name: VT_MEM
                value: "4"
              - name: VT_REDIS_LIST_NAME
                value: "jobs_create_sample"
            resources:
              limits:
                cpu: 2700m
                memory: 5Gi
              requests:
                cpu: 2700m
                memory: 5Gi
  triggers:
  - metadata:
      listName: "jobs_create_sample"
