apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app.virtool.ca/workflow-name: create-subtraction
    app.virtool.ca/workflow-size: small
  name: create-subtraction
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: workflow-create-subtraction
      spec:
        containers:
          - name: workflow-create-subtraction
            image: ghcr.io/virtool/create-subtraction:5.3.3
            env:
              - name: VT_PROC
                value: "2"
              - name: VT_MEM
                value: "2"
              - name: VT_REDIS_LIST_NAME
                value: "jobs_create_subtraction"
            resources:
              limits:
                cpu: "3"
                memory: 5Gi
              requests:
                cpu: "3"
                memory: 5Gi
  triggers:
  - metadata:
      listName: "jobs_create_subtraction"
