apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: pathoscope
  labels:
    app.virtool.ca/workflow-name: pathoscope
    app.virtool.ca/workflow-size: large
spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - name: workflow-pathoscope
            image: ghcr.io/virtool/pathoscope:5.9.4
            env:
              - name: VT_MEM
                value: "8"
              - name: VT_PROC
                value: "4"
              - name: VT_REDIS_LIST_NAME
                value: "jobs_pathoscope_bowtie"
            resources:
              limits:
                cpu: "5"
                memory: 10Gi
              requests:
                cpu: "5"
                memory: 10Gi
  triggers:
  - metadata:
      listName: "jobs_pathoscope_bowtie"
