apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtool-task-runner
spec:
  template:
    spec:
      containers:
        - name: virtool
          command: ["virtool", "tasks", "runner"]
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 600m
              memory: 1Gi
