labels:
  - pairs:
      app: virtool-task-runner
    includeTemplates: true
    includeSelectors: true

patches:
  - path: deployment.yaml
    target:
      kind: Deployment
    options:
      allowNameChange: true
  - target:
      kind: Service
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: ignored

resources:
  - ../../base